// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/home/hitesh/actNumber/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import DashboardOutlined from '/home/hitesh/actNumber/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import FormOutlined from '/home/hitesh/actNumber/node_modules/@ant-design/icons/es/icons/FormOutlined';
import TableOutlined from '/home/hitesh/actNumber/node_modules/@ant-design/icons/es/icons/TableOutlined';
import ProfileOutlined from '/home/hitesh/actNumber/node_modules/@ant-design/icons/es/icons/ProfileOutlined';
import CheckCircleOutlined from '/home/hitesh/actNumber/node_modules/@ant-design/icons/es/icons/CheckCircleOutlined';
import WarningOutlined from '/home/hitesh/actNumber/node_modules/@ant-design/icons/es/icons/WarningOutlined';
import UserOutlined from '/home/hitesh/actNumber/node_modules/@ant-design/icons/es/icons/UserOutlined';
export default { SmileOutlined, DashboardOutlined, FormOutlined, TableOutlined, ProfileOutlined, CheckCircleOutlined, WarningOutlined, UserOutlined };
